
eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone : http://${eureka.instance.hostname}:${server.port}/eureka/

server:
  port: 8090
spring:
  config:
    import: optional:configserver:http://localhost:8888

